import "./globals.css";
import type { Metadata } from "next";
import Link from "next/link";
import { getGeneratedAt, getDataSource } from "../lib/data";

export const metadata: Metadata = {
  title: "CEEW Bill Tracker — Climate Impact Register",
  description:
    "Parliamentary bills tracked and scored for climate-policy relevance, for CEEW's outreach team.",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const generatedAt = getGeneratedAt();
  const source = getDataSource();

  return (
    <html lang="en">
      <body className="font-body min-h-screen flex flex-col">
        <header className="border-b border-rule bg-card">
          <div className="max-w-5xl mx-auto px-6 py-5 flex items-baseline justify-between">
            <Link href="/" className="group">
              <div className="font-mono text-[11px] tracking-widest uppercase text-orange">
                CEEW &middot; Outreach
              </div>
              <div className="font-display text-2xl font-semibold text-ink">
                Bill Climate&#8209;Impact Register
              </div>
            </Link>
            <div className="flex items-center gap-5">
              <Link href="/" className="text-sm font-mono text-inkmuted hover:text-ink">
                Bills
              </Link>
              <Link href="/trends" className="text-sm font-mono text-inkmuted hover:text-ink">
                Trends
              </Link>
              <Link href="/qa" className="text-sm font-mono text-inkmuted hover:text-ink">
                Q&amp;A
              </Link>
              <Link href="/about" className="text-sm font-mono text-inkmuted hover:text-ink">
                About
              </Link>
              <div className="text-right font-mono text-[11px] text-inkmuted hidden sm:block">
                data as of {new Date(generatedAt).toLocaleDateString("en-IN", {
                  year: "numeric",
                  month: "short",
                  day: "numeric",
                })}
              </div>
            </div>
          </div>
        </header>

        <main className="flex-1">{children}</main>

        <footer className="border-t border-rule mt-16">
          <div className="max-w-5xl mx-auto px-6 py-6 text-xs text-inkmuted font-mono leading-relaxed">
            <p>
              Bill data sourced from{" "}
              <a
                className="underline hover:text-ink"
                href="https://prsindia.org/billtrack"
                target="_blank"
                rel="noreferrer"
              >
                PRS Legislative Research
              </a>{" "}
              ({source}). Climate-impact scores are generated by an AI model against a
              rubric CEEW&rsquo;s outreach team designed, and may be manually reviewed or
              corrected — see the confidence flag on each bill.
            </p>
          </div>
        </footer>
      </body>
    </html>
  );
}
